# Generated by Django 4.2.17 on 2025-11-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0010_reportentry_ml_valid_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpikeDetectionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.FloatField(help_text='Ratio used to mark a day as spike')),
                ('short_window_start', models.DateField(help_text='Start date of the short window')),
                ('short_window_end', models.DateField(db_index=True, help_text='End date of the short window')),
            ],
        ),
        migrations.CreateModel(
            name='BucketSpike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_count', models.IntegerField(help_text='Number of reports in the short window')),
                ('short_count_with_comments', models.IntegerField(help_text='Number of reports with non-empty comments in the short window')),
                ('short_average', models.FloatField()),
                ('long_average', models.FloatField()),
                ('ratio', models.FloatField()),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportmanager.bucket')),
                ('detection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spikes', to='reportmanager.spikedetectionrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='bucketspike',
            constraint=models.UniqueConstraint(fields=('detection_run', 'bucket'), name='unique_spike_per_run_bucket'),
        ),
    ]
