# Generated by Django 4.2.27 on 2026-01-26 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0010_reportentry_ml_valid_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('centroid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centroid_of', to='reportmanager.reportentry')),
            ],
        ),
        migrations.AddField(
            model_name='reportentry',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportmanager.cluster'),
        ),
        migrations.AddIndex(
            model_name='cluster',
            index=models.Index(fields=['domain'], name='reportmanag_domain_775a6e_idx'),
        ),
    ]
