# Generated by Django 6.0.2 on 2026-02-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0011_cluster_reportentry_cluster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteringJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('full', 'Full Clustering'), ('incremental', 'Incremental Triage')], default='full', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_ok', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('buckets_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bucket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
