# Generated by Django 6.0.2 on 2026-02-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0012_clusteringjob_alter_bucket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportentry',
            name='comments_preprocessed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reportentry',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='reportentry',
            index=models.Index(fields=['domain'], name='reportmanag_domain_8c4b7c_idx'),
        ),
    ]
