# Generated by Django 6.0.2 on 2026-02-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0012_clusteringjob_alter_bucket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportentry',
            name='comments_preprocessed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='reportentry',
            name='domain',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
