# Generated by Django 6.0.2 on 2026-03-02 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0014_populate_domain_and_preprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buckets', to='reportmanager.cluster'),
        ),
    ]
