# Generated by Django 6.0.3 on 2026-03-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0015_bucket_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock_name', models.CharField(max_length=50, unique=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('acquired_by', models.CharField(help_text='hostname:pid of process holding lock', max_length=255)),
            ],
        ),
    ]
