# Generated by Django 6.0.3 on 2026-04-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0016_joblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportentry',
            name='country',
            field=models.TextField(max_length=2, null=True),
        ),
    ]
