# Generated by Django 6.0.4 on 2026-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0017_reportentry_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='triage_status',
            field=models.CharField(choices=[('worksforme', 'Works For Me'), ('cant_test', "Can't Test"), ('incomplete', 'Incomplete'), ('invalid', 'Invalid'), ('non_compat', 'Non-Compat')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='triaged_at',
            field=models.DateTimeField(null=True),
        ),
    ]
