# Generated by Django 6.0.4 on 2026-04-24 17:02

from django.db import migrations
from django.utils import timezone


def migrate_triage_data(apps, schema_editor):
    """Migrate hide_until data to triage_status field."""
    Bucket = apps.get_model('reportmanager', 'Bucket')
    now = timezone.now()

    # All currently triaged buckets (hide_until is not NULL) → 'worksforme'
    triaged_count = Bucket.objects.filter(hide_until__isnull=False).update(
        triage_status='worksforme',
        triaged_at=now
    )

    print(f"Migrated {triaged_count} triaged buckets to 'worksforme' status")


def reverse_migrate(apps, schema_editor):
    """Reverse migration - clear triage_status."""
    Bucket = apps.get_model('reportmanager', 'Bucket')
    Bucket.objects.all().update(triage_status=None, triaged_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0018_add_triage_status'),
    ]

    operations = [
        migrations.RunPython(migrate_triage_data, reverse_migrate),
    ]
