# Generated by Django 6.0.4 on 2026-04-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0019_migrate_hide_until_to_triage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='hide_until',
        ),
    ]
