# Generated by Django 6.0.5 on 2026-05-21 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0020_remove_hide_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('bq_table', models.CharField(max_length=500)),
                ('bq_source_field', models.CharField(max_length=255)),
                ('last_synced_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DomainEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('domain_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reportmanager.domainsource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('domain_source', 'domain'), name='unique_domain_per_source')],
            },
        ),
    ]
