# Generated by Django 6.0.5 on 2026-05-26 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0021_domainsource_domainentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='domain_normalized',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('domain_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label', to='reportmanager.domainsource')),
            ],
        ),
        migrations.CreateModel(
            name='BucketLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='reportmanager.bucket')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_labels', to='reportmanager.label')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bucket', 'label'), name='unique_bucket_label')],
            },
        ),
    ]
