# Generated by Django 6.0.5 on 2026-06-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0023_backfill_domain_normalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='BucketCountryRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_ranks', to='reportmanager.bucket')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bucket', 'country'), name='unique_bucket_country_rank')],
            },
        ),
    ]
