# Generated by Django 6.0.5 on 2026-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0024_bucketcountryrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketcountryrank',
            name='import_id',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
