# Generated by Django 6.0.5 on 2026-06-17 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportmanager', '0024_bucketcountryrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketcountryrank',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
